/// @description Вставьте описание здесь
// Вы можете записать свой код в этом редакторе
depth = -999
xx = 0
drag_offset_x = 0;
drag_offset_y = 0;
drag_x = x;
drag_y = y;
drag = false;
dir = 0
moving = false
hsp = 0
vsp = 0
move =false
dr = false
loop = 1
looped = 0
text = "Loop"
c_objects = []
completed = false
creator = noone
loopend = noone
out = false
alarm[0] = 2
dx = 0
dy = 0
drag_objects = []
prevorder = 0
place = false;